### ISSUE TITLE
NoMethodError: undefined method `blank?' for "":String

### ISSUE THREAD

**Issue by mdaines-r7** [rapid7/rex#1]
Several places in the code expect there to be a `String#blank?` method. None of the dependencies pull in this monkey patch to the String class.

Easiest fix may be to just add this to _rex.rb_:

``` ruby
class String
  def blank?
    self !~ /\S/
  end
end
```

**Comment by hdm** [comment]
This is an ActiveSupport dependency and Rex classes should be not be depending on these methods. Removing .blank? calls would be preferable to extending String. This change would need to be made in the upstream metasploit-framework repository (rex is a subset of metasploit-framework right now). Please open this ticket under the framework repository.

**Comment by erran-r7** [comment]
@hmoore-r7 the rex gem is used as a dependency in [rapid7/nexpose-client](https://github.com/rapid7/nexpose-client). `Rex::MIME` is the only class used. I'm considering replacing them since rex seems tightly coupled to metasploit-framework still. It'd be great if we could remove that coupling, but I understand that isn't necessarily a priority.

**Comment by hdm** [comment]
PRd in metasploit-framework as https://github.com/rapid7/metasploit-framework/pull/4848

**Comment by trosen-r7** [comment]
@erran-r7 your solution is the correct one. Rex is indeed still tightly coupled to Metasploit framework and should not be used in a standalone way for use cases this narrow.
